// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPj4E-_OJpgPv6tuFQvDmEYBWH7xeKsYA',
    appId: '1:711655799596:web:bb66809b6599e403cfca89',
    messagingSenderId: '711655799596',
    projectId: 'kamp-karavan-79a7e',
    authDomain: 'kamp-karavan-79a7e.firebaseapp.com',
    storageBucket: 'kamp-karavan-79a7e.firebasestorage.app',
    measurementId: 'G-4JHFXBGZ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjo1ZltJWUC8OSG4yKVUtYuLZnI298JdU',
    appId: '1:711655799596:android:90c26916a256c0becfca89',
    messagingSenderId: '711655799596',
    projectId: 'kamp-karavan-79a7e',
    storageBucket: 'kamp-karavan-79a7e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMy3_2hILNiN-UFLPuUuzrxv_g69XVznY',
    appId: '1:711655799596:ios:2a02a8ce806dd586cfca89',
    messagingSenderId: '711655799596',
    projectId: 'kamp-karavan-79a7e',
    storageBucket: 'kamp-karavan-79a7e.firebasestorage.app',
    iosBundleId: 'com.mndrs.karavanis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPj4E-_OJpgPv6tuFQvDmEYBWH7xeKsYA',
    appId: '1:711655799596:web:fbff3149d4615d14cfca89',
    messagingSenderId: '711655799596',
    projectId: 'kamp-karavan-79a7e',
    authDomain: 'kamp-karavan-79a7e.firebaseapp.com',
    storageBucket: 'kamp-karavan-79a7e.firebasestorage.app',
    measurementId: 'G-67CL9ER7CF',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMy3_2hILNiN-UFLPuUuzrxv_g69XVznY',
    appId: '1:711655799596:ios:2a02a8ce806dd586cfca89',
    messagingSenderId: '711655799596',
    projectId: 'kamp-karavan-79a7e',
    storageBucket: 'kamp-karavan-79a7e.firebasestorage.app',
    iosBundleId: 'com.mndrs.karavanis',
  );
}
