platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # 🔥 Flutter betiklerine güvenmek yerine paketleri doğrudan pod olarak kuruyoruz
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'supabase_flutter', :path => '.symlinks/plugins/supabase_flutter/ios'
  pod 'app_links', :path => '.symlinks/plugins/app_links/ios'
  pod 'flutter_local_notifications', :path => '.symlinks/plugins/flutter_local_notifications/ios'
  pod 'image_picker_ios', :path => '.symlinks/plugins/image_picker_ios/ios'
  pod 'url_launcher_ios', :path => '.symlinks/plugins/url_launcher_ios/ios'
  pod 'flutter_image_compress_common', :path => '.symlinks/plugins/flutter_image_compress_common/ios'
  pod 'path_provider_foundation', :path => '.symlinks/plugins/path_provider_foundation/ios'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end